---
name: PlantUML Composite Action test

on:
  push:
    paths:
      - 'docs/**.puml'
  pull_request:
    paths:
      - 'docs/**.puml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  plantuml:
    runs-on: ubuntu-latest

    steps:
      - name: Generate PUML diagrams
        if: github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork
        uses: theboutroslab/tool-PlantUML-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ghcr-username: ${{ github.actor }}
          ghcr-password: ${{ secrets.GITHUB_TOKEN }}
